---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-app
        image: jarrodkim/fastapi-backend:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: mariadb
        - name: DB_USER
          value: fcgiuser
        - name: DB_PASSWORD
          value: fcgipass
        - name: DB_NAME
          value: fcgidb
        volumeMounts:
        - name: app-code
          mountPath: /app
      volumes:
      - name: app-code
        configMap:
          name: auth-service

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service
data:
  main.py: |
    from fastapi import FastAPI, Form , HTTPException
    import pymysql

    app = FastAPI()

    @app.post("/api/auth/register")
    async def register(username: str = Form(...), password: str = Form(...)):
        conn = pymysql.connect(
            host="mariadb",
            user="fcgiuser",
            password="fcgipass",
            database="fcgidb"
        )
        with conn.cursor() as cursor:
            cursor.execute("INSERT INTO users (username, password) VALUES (%s, %s)", (username, password))
        conn.commit()
        return {"message": "가입 완료!"}

    @app.post("/api/auth/login")
    async def login(username: str = Form(...), password: str = Form(...)):
        conn = pymysql.connect(
            host="mariadb",
            user="fcgiuser",
            password="fcgipass",
            database="fcgidb"
        )
        with conn.cursor() as cursor:
            cursor.execute("SELECT * FROM users WHERE username=%s AND password=%s", (username, password))
            result = cursor.fetchone()
        if result:
            return {"message": "로그인 성공"}
        else:
            raise HTTPException(status_code=401, detail="로그인 실패")
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - port: 8000
    targetPort: 80
~
